_wandb:
    value:
        cli_version: 0.22.2
        e:
            694mx0plv0kbzq4acbd1rsuavz95uvnq:
                args:
                    - --config
                    - configs/vae/ss_vae_conv3d_16l8_fp16.json
                    - --output_dir
                    - /root/node1/data3/shape-generation/TRELLIS/outputs
                    - --num_gpus
                    - "2"
                    - --data_dir
                    - /root/node1/data3/shape-generation/shapenetv1/voxelized_pcs_uniform_light
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1005867986944"
                        used: "718731472896"
                email: wjsduddn0709@naver.com
                executable: /opt/conda/bin/python
                git:
                    commit: b3e26c66b3a75610c5f45d5016555a022188045f
                    remote: git@github.com:wowo0709/TRELLIS.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 7
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-d04f1c5c-bc32-4e3d-75ff-59023dd60152
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a0646e1d-6308-0999-dc81-967bf1c6adbe
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-ea0fc3b1-6762-928c-f83d-0843a0c7a1db
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-94616280-14a7-1c23-9d93-970d420e2b61
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-5afb1422-01b2-8812-78b1-f0940a82fb3a
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-75e3e16e-edbe-b9a7-76ca-76e7181db596
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-21db9f27-c6fb-47f1-18ad-a6ab1b0161df
                host: cd7bdbb909d0
                memory:
                    total: "404261466112"
                os: Linux-6.8.0-84-generic-x86_64-with-glibc2.35
                program: /root/dev/TRELLIS/train.py
                python: CPython 3.11.9
                root: /root/dev/TRELLIS
                startedAt: "2025-10-22T05:49:58.144266Z"
                writerId: 694mx0plv0kbzq4acbd1rsuavz95uvnq
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
            "4": 3.11.9
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
